# Generated by Django 4.2.1 on 2023-05-29 13:22

import django.core.validators
from django.db import migrations, models
import my_plant_app.main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app.main.validators.cap_first_validator])),
                ('last_name', models.CharField(max_length=20, validators=[my_plant_app.main.validators.cap_first_validator])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
