# Generated by Django 4.2.1 on 2023-05-24 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('year', models.IntegerField()),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
