# Generated by Django 4.2.2 on 2023-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='asd', max_length=15),
            preserve_default=False,
        ),
    ]
