# Generated by Django 4.2.2 on 2023-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_nullblankdemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='null',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
