# Generated by Django 4.2.2 on 2023-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_nullblankdemo_blank_remove_nullblankdemo_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('reg', 'Regular'), ('sr', 'Senior')], max_length=3),
        ),
    ]
