# Generated by Django 4.2.2 on 2023-06-15 14:31

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    Department = apps.get_model("web", "Department")

    departments = Department.objects.all()

    for department in departments:
        department.slug = slugify(department.name)

    Department.objects.bulk_update(departments, ['slug'])


def delete_slug(apps, schema_editor):
    Department = apps.get_model("web", "Department")

    departments = Department.objects.all()

    for department in departments:
        department.slug = None

    Department.objects.bulk_update(departments, ['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0028_department_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, delete_slug),
    ]
