# Generated by Django 4.2.1 on 2023-05-23 11:14

import django.core.validators
from django.db import migrations, models
import my_music_app.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.web.models.validate_only_alphanumeric]),
        ),
    ]
